# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_writer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
